### ISSUE TITLE
DeltaVision website links, no longer api.com, rather redirects/moved to GE website 

### ISSUE THREAD

**Issue by chalkie666** [openmicroscopy/bioformats#1581]
DeltaVision website links, no longer api.com, rather moved to GE website 
currenty
http://www.gelifesciences.com/webapp/wcs/stores/servlet/catalog/en/GELifeSciences-de/products/AlternativeProductStructure_23807/
so bioformats info pages7files about DV file format might like to be updated with that info
api.com now redirects there
cheers
Dan

**Comment by hflynn** [comment]
Thanks for reporting this, I'll update the links this week.

**Comment by hflynn** [comment]
PR opened, whoever has permission can close this now. Thanks again @chalkie666
