### ISSUE TITLE
Metadata skew in Bioformats for LightsheetZ1 CZI data

### ISSUE THREAD

**Issue by StephanPreibisch** [openmicroscopy/bioformats#1782]
Hi,

I realized that different versions of Bioformats store the individual stack size for the views under different tags. I implemented a workaround here https://github.com/bigdataviewer/SPIM_Registration/commit/d10db40f989c20ec07b3d615f4a2965e20c573d2, but it seems that this is not right.

In the current Fiji there is Bioformats-5.1.1. and it stores the z-stack size metadata under the key:
SizeZ|View|V|Image|Information #1
SizeZ|View|V|Image|Information #2
SizeZ|View|V|Image|Information #3
...

In Eclipse I still use Bioformats-5.1.0 where the key is
Information|Image|V|View|SizeZ #1
Information|Image|V|View|SizeZ #2
Information|Image|V|View|SizeZ #3
...

Or is this change on purpose?

Thanks a lot, Stephan

**Comment by melissalinkert** [comment]
Thanks for point this out, @StephanPreibisch.  This was not intentional; the proposed fix is in gh-1784.

**Comment by melissalinkert** [comment]
Closing, as the corresponding fix has been tested and merged for 5.1.2.
