### ISSUE TITLE
incorrect reading of indexed bmp files

### ISSUE THREAD

**Issue by carandraug** [openmicroscopy/bioformats#1887]
[This image](http://www.mediafire.com/view/0xnqejy3m7ef24v/foo.bmp) (I don't have flash installed so I could not upload to the QA tracker) is read incorrectly by bioformats. Gnome image viewer, graphicsmagick, and imagemagick all handle it correctly.

    $ gm identify -verbose /tmp/foo.bmp 
    Image: /tmp/foo.bmp
      Format: BMP (Microsoft Windows bitmap image)
      Geometry: 256x100
      Class: PseudoClass
      Type: palette
      Depth: 8 bits-per-pixel component
      Channel Depths:
        Red:      8 bits
        Green:    8 bits
        Blue:     8 bits
      Colors: 256
        0: (255,  0,  0)	  red
        1: (255,  2,  0)	  #FF0200
        2: (255,  5,  0)	  #FF0500
        [...]
        255: (170,  0,255)	  #AA00FF
      Resolution: 29.25x29.25 pixels/centimeter
      Filesize: 51.2Ki
      Interlace: No
      Orientation: Unknown
      Background Color: white
      Border Color: #DFDFDF
      Matte Color: #BDBDBD
      Page geometry: 256x100+0+0
      Compose: Over
      Dispose: Undefined
      Iterations: 0
      Compression: Undefined
      Signature: 0a4fffb86e1d6dc8c67a8e04e2c3a63ca3c1576d9f59bb268f6a3a877e1b6ed6
      Tainted: False

**Comment by mtbc** [comment]
Thank you very much indeed, especially for the simple example. I have logged the bug as http://trac.openmicroscopy.org/ome/ticket/12971 and added you to the cc: list so that you are notified of our progress on it. Okay to close this issue?
