### ISSUE TITLE
Deploy on maven central?

### ISSUE THREAD

**Issue by avandecreme** [openmicroscopy/bioformats#2048]
Any plan to do that?

**Comment by joshmoore** [comment]
Hi @avandecreme. There are certainly plans, but first we are in the process cleaning up dependencies to be able to summit. In the meantime, would jars on https://bintray.com/ be useful?

**Comment by avandecreme** [comment]
Hi @joshmoore Great to know there is a plan for it.
I am fine using the [open microscopy repository](http://artifacts.openmicroscopy.org/artifactory/ome.releases) for now.
