### ISSUE TITLE
Split Channels setting is persistent when it shouldn't be

### ISSUE THREAD

**Issue by nashv** [openmicroscopy/bioformats#2057]
Hello, 
I’ve encountered  the following behavior difference in calling Bio-formats manually versus from a macro. If someone runs Bio-Formats from the plugins menu and checks ‘split_channels’, that option is not cleared if subsequently Bio-formats is called from a macro that is not intended to split channels.   

for example, run from macro to split channels: 
 run(“Bio-Formats Importer”,”open=[bunchastuff] color_moded=Grayscale split_channels view=Hyperstack stack_order=default”); -> splits channels 

then  run from macro to NOT split channels: 
 run(“Bio-Formats Importer”,”open=[bunchastuff] color_moded=Grayscale  view=Hyperstack stack_order=default”); -> does not split channels 

Now, open Bio-Formats from plugins menu, manually select ‘split channels’ -> splits channels 

then run from macro to NOT split channels: 
 run(“Bio-Formats Importer”,”open=[bunchastuff] color_moded=Grayscale  view=Hyperstack stack_order=default”); ->  still splits channels 

Is there a way around this?

**Comment by melissalinkert** [comment]
https://github.com/openmicroscopy/bioformats/pull/2061, which was included in 5.1.6, should have resolved this problem.  Please feel free to reopen if the problem persists.
