### ISSUE TITLE
Micromanager tiff files

### ISSUE THREAD

**Issue by avandecreme** [openmicroscopy/bioformats#2163]
Hello,

I have 2 questions regarding micromanager tiff files support.

1. It looks like all the "StageLabel" informations could be retrieved from the JSON file with the properties XPositionUm, YPositionUm and ZPositionUm.
Is there any reason I don't know about to not support it?

2. The JSON file is stored inside the TIFF file in the tags 50838 and 50839. Those are ImageJ tags and the implementation is available here:
https://github.com/imagej/ImageJA/blob/v1.48e/src/main/java/ij/io/TiffDecoder.java#L43
Would it be possible to support reading the JSON file from there if the metadata.txt file is missing?

**Comment by melissalinkert** [comment]
Thanks for bringing this up, @avandecreme.  We'd be happy to update the Micromanager reader to fix both points - there isn't a reason they aren't supported apart from lack of resources.  I've added this to our list of things to look at for the 5.2.0 release of Bio-Formats:

https://trello.com/c/499UGA5U/72-micromanager-stage-positions-and-json
