### ISSUE TITLE
VSI Files open much more slowly than before

### ISSUE THREAD

**Issue by lacan** [openmicroscopy/bioformats#2358]
Hi, 
We have been using the CellSens Reader coupled to the Macro Extensions for Fiji/ImageJ. 

This has been working fine till about last month perhaps when now it takes minutes to open even a very small image. What has changed?
We are using the version from your update site: 14 April 2016. 
Best
Oli

**Comment by sbesson** [comment]
Closing in favor of discussion on the [forum thread](https://www.openmicroscopy.org/community/viewtopic.php?f=13&t=7501&p=16992#p16991).
