### ISSUE TITLE
SVS to TIFF conversion is failling

### ISSUE THREAD

**Issue by felixveysseyre** [openmicroscopy/bioformats#2366]
Thanks for your awesome tool !

I have been trying to convert to TIFF numerous SVS files with _bfconvert_.
They all seem corrupted.

Here is the result (opened with _GIMP_) of the conversion of http://openslide.cs.cmu.edu/download/openslide-testdata/Aperio/JP2K-33003-1.svs:

<img width="847" alt="svs-fail" src="https://cloud.githubusercontent.com/assets/4909259/14714616/f8654172-07e5-11e6-976f-346f46c91823.png">

Here is the command line I have been using:
`.../bfconvert -bigtiff -series 0 ".../JP2K-33003-1.svs" ".../%z.%t.%c.tiff"`

I am using latest _bftools_ on _Mac OS X 10.11_ (but same thing is happening on _Ubuntu 14.04_):
```
felixveysseyre$ ./bfconvert -version
Version: 5.1.9
VCS revision: c3065feb775a7a8c0cc2cf6e35979331cca2418b
Build date: 15 April 2016
```

Thanks for your help !

**Comment by sbesson** [comment]
Closing in favor of duplicate [forum post](https://www.openmicroscopy.org/community/viewtopic.php?t=8042&p=17018#p17018)
