### ISSUE TITLE
bioformats exporter plugin freezes on mac

### ISSUE THREAD

**Issue by gatagat** [openmicroscopy/bioformats#2655]
Trying to save an image using bioformats exporter plugin in Fiji on Mac OS, makes Fiji to freeze. No dialog window to select the output filename appears, Fiji becomes unresponsive and has to be killed.

Bioformats version: 5.2.4
Mac OS: 10.11.6
Fiji downloaded on Nov 3 2016

**Comment by mtbc** [comment]
I am sorry to hear that you are running into this problem. We have also seen it reported in #2238 and elsewhere. Thank you for providing the version information, that's always helpful. I'll add a note of this issue to the card at https://trello.com/c/L7dtKWsl/22-bio-format-exporter-issues on which we are tracking this and, as a confirmed serious problem, we intend to prioritize the work to fix this.
