### ISSUE TITLE
BioFormats 5.5.3 does not read CZI metainfo (series number, pyramid levels) correctly anymore

### ISSUE THREAD

**Issue by sebi06** [openmicroscopy/bioformats#2898]
Hi guys,

I just tries to use Grid-Stitching in Fiji to stitch the CZI (see link) to check if this plugin can deal with BioFormats feature to read CZI pyramid levels.
 It did not work because the plugin claimed this file has only 5 series. But it is a 15x8 TileRegion.

https://www.dropbox.com/s/kytfnxf2dpywzf7/15x8_Tileregion.czi?dl=0

Error Message:
ERROR: Inconsistent series layout. Metadata says 5 tiles, but contains only 120 images/tiles.
ERROR: Error during tile discovery, or invalid grid type. Aborting.

![15x8_tileregion_czi](https://user-images.githubusercontent.com/3833249/28266453-3f1e99b0-6af5-11e7-897d-5a8ccb3f529c.png)

I tested this using BioFormats 5.1.10 and got what I expected 120 Tiles.

![15x8_tileregion_czi_bf_5 1 10](https://user-images.githubusercontent.com/3833249/28266539-b2c47b96-6af5-11e7-90e3-806cad9b0108.png)

When I do the same using BioFormats 5.5.3 i get only 5 series, which of course is not correct. So something went wrong when reading the data. This image has of course some pyramid levels, but at full resolution there are 120 tiles. Obviously this beraks a lot of existing workflows if that is really true ...

![15x8_tileregion_czi_bf_5 5 3](https://user-images.githubusercontent.com/3833249/28266704-a52fc0f2-6af6-11e7-8eb1-fced6235111a.png)

And it raises the additional question, if the Grid-Stitching plugin makes use of the Bioformats option to only read the full-res level of the pyramid.

**Comment by sbesson** [comment]
Hi @sebi06, you are correct that the total number and dimensions of the series is now dependent on the reader options while in Bio-Formats 5.1.10, the only available possibility was to read individual tiles. Using the sample file you provided and varying the [Zeiss CZI options](http://docs.openmicroscopy.org/bio-formats/5.5.3/formats/options.html), I have the following results:

```
sbesson@ls30630:Downloads $ showinf -nopix -nometa 15x8_Tileregion.czi | grep Series\ c
Series count = 5
sbesson@ls30630:Downloads $ showinf -nopix -nometa -option zeissczi.autostitch false 15x8_Tileregion.czi | grep Series\ c
Series count = 121
sbesson@ls30630:Downloads $ showinf -nopix -nometa -option zeissczi.autostitch false -option zeissczi.attachments false 15x8_Tileregion.czi | grep Series\ c
Series count = 120
```

For the Grid-Stitching plugin, as the code is using [BF.openImagePlus()](https://github.com/fiji/Stitching/blob/Stitching_-3.1.3/src/main/java/plugin/Stitching_Grid.java#L840) for initializing the reader, I would expect that unchecking the `Automatically stitch tiled images` and `Include attachment images` checkboxes for the Zeiss CZI format in the Configuration window should be sufficient to allow the plugin to read the data in the expected layout. Could you check this? /cc @StephanPreibisch

**Comment by sebi06** [comment]
This is what I already tried yesterday, but it does not work.

![stitch_problem](https://user-images.githubusercontent.com/3833249/28315697-e63eba48-6bbf-11e7-9458-00e530323f95.png)

But I think the Grid Stitching is just no aware of this since it counts the image attachment and the actual 4 pyramid levels while BioFormats 5.5.3 actually correctly got 4 real series.

![image](https://user-images.githubusercontent.com/3833249/28315772-473c6732-6bc0-11e7-88b8-bb0ef1340bae.png)

**Comment by sbesson** [comment]
Thanks for checking and for the debugging screenshots. I think they help identifying the source of the problem.

The error message informs about a failing [check](https://github.com/fiji/Stitching/blob/Stitching_-3.1.3/src/main/java/plugin/Stitching_Grid.java#L1006) between the size of two lists:

- `imps` is an array of `ImagePlus` objects created using `BF.openImagePlus()` which internally consumes the options defined in the ImageJ configuration window
- `elements` is ArrayList of ImageCollectionElement objects created in another call to the low-level Bio-Formats API notably and notably the [creation of a separate reader](https://github.com/fiji/Stitching/blob/master/src/main/java/plugin/Stitching_Grid.java#L863)

The two reader stacks are created independently and in the context of this issue, the main problem is that they have mismatching options. There are a few ways here to tackle this issue in the Grid Stitching plugin:

- the immediate workaround is be to copy the logic in [LociPrefs](https://github.com/openmicroscopy/bioformats/blob/v5.5.3/components/bio-formats-plugins/src/loci/plugins/util/LociPrefs.java#L96)  and set the same metadata options
- it might be possible to introspect the options of the reader created by `BF.openImagePlus()` but that would require a bit more reorganization in the Grid Stitching code
- there might be case for a new API that would either return the `MetadataOptions` defined by the Configuration window or apply them to a reader although this would require more discussion and scoping.

**Comment by zeissmicroscopy** [comment]
Hi Sebastian,

if I understood you correctly this workaround would be to modify the BioFormats sourceCode directly, right? But I would be better, if the Grid Stitching plugin could be modified so that it works with the latest BioFormats and CZI in my opinion. So maybe I should file a request for that (but where? Bug Entry)?

And the workaround does not really solve the issues that users currently using CZIs and GridStitching are still stuck. 

What about downgrading to Bioformats 5.1.10 as the last (emergency) option?

**Comment by imagejan** [comment]
@zeissmicroscopy wrote:
> So maybe I should file a request for that (but where? Bug Entry)?

PRs are accetped at https://github.com/fiji/Stitching/pulls, and issues can be filed here: https://github.com/fiji/Stitching/issues

**Comment by sbesson** [comment]
@ zeissmicroscopy: for this particular issue, the fix has to be applied at the Grid Stitching plugin source code level in order to ensure that the two readers are created with the same options - ideally the ones set up by the user in the Configuration window. In that sense, I am closing this issue in favor of https://github.com/fiji/Stitching/issues/42 that you opened and we will start watching it for any API discussion.
