### ISSUE TITLE
Physical size units issue with Fiji

### ISSUE THREAD

**Issue by ehrenfeu** [openmicroscopy/bioformats#3127]
Hi all,

I'm experiencing an issue with the units stored by BF when exporting an image from (an up-to-date) Fiji. When setting the "Unit of length" to `nm` or [`nanometre`](https://en.wikipedia.org/wiki/Nanometre) (which are correctly recognized by Fiji), then exporting and re-importing it with Bio-Formats, the `PhysicalSizeXUnit` is reported as `µm` (or `microns`) - while being inconsistent with the "Image Properties" dialog of Fiji (the latter still displaying `nm`).

Checking the OME-XML generated by the BF exporter reveals that the physical unit stored there is actually `µm` whereas it should be rather `nm`.

The following IJ1 macro demonstrates this issue:

```javascript
TMPNAME = "/tmp/physical_units_test.ome.tif";

function print_calibration() {
    getPixelSize(unit, pw, ph, pd);
    print("Pixel size (" + getTitle() + "):  x=" + pw + unit + " y=" + ph + unit);
}

run("Close All");
print("\\Clear");

newImage("orig", "8-bit white", 30, 20, 1);
run("Properties...", "unit=nm pixel_width=100 pixel_height=100");
run("Bio-Formats Exporter", "save=" + TMPNAME);
print_calibration();

run("Bio-Formats Importer", "open=" + TMPNAME);
rename("reloaded");
print_calibration();

run("Properties...", "unit=nm pixel_width=100 pixel_height=100");
rename("recalibrated");
print_calibration();
```

Resulting output is:
```
Pixel size (orig):  x=100nm y=100nm
Pixel size (reloaded):  x=100microns y=100microns
Pixel size (recalibrated):  x=100nm y=100nm
```

Any hints?

Cheers,
Niko

**Comment by dgault** [comment]
Hi @ehrenfeu,

I can certainly reproduce the same behaviour as you are seeing. From some initial debugging it looks as though the Exporter in the Bio-Formats plugin is specifically choosing not to apply the calibration. Quickly testing an override of this has resulted in a `NullPointerException` so I shall have to continue debugging this further. I will take a more detailed look into this tomorrow and update with any progress.

**Comment by melissalinkert** [comment]
Thanks again for reporting this, @ehrenfeu.  Closing in favor of proposed fix in https://github.com/openmicroscopy/bioformats/pull/3295; happy to continue the discussion there.
