### ISSUE TITLE
Error while reading .dm4 files

### ISSUE THREAD

**Issue by adroitanup** [openmicroscopy/bioformats#3188]
Is there a way to read .dm4 files using bioformats? I keep on getting an error.
![image](https://user-images.githubusercontent.com/41760171/43286350-5a836c58-90e7-11e8-8117-1e35244b732b.png)

**Comment by dgault** [comment]
Hi @adroitanup, .dm4 files should be supported. If you have a sample file you can upload to https://www.openmicroscopy.org/qa2/qa/upload/ I would be happy to test it for you to see what is causing the problem.

**Comment by melissalinkert** [comment]
Thanks again for reporting this, @adroitanup.  https://github.com/openmicroscopy/bioformats/pull/3288 seems to have fixed part of the problem; https://github.com/openmicroscopy/bioformats/pull/3294 should fix the remainder.

Closing in favor of https://github.com/openmicroscopy/bioformats/pull/3294 - we'll update there with any testing progress.
