### ISSUE TITLE
MetamorphReader inconsistently reads image titles

### ISSUE THREAD

**Issue by imagejan** [openmicroscopy/bioformats#3216]
The image title of Metamorph datasets read by Bio-Formats depends on the presence of other files in the source folder: if only the target dataset (i.e. `nd` and `stk` files) is present, the title correctly reflects the name of the first `stk` file; when other files are present, the image title is taken from an unrelated file, even though the pixel data are correctly read from the target dataset.

This is related to https://github.com/openmicroscopy/bioformats/issues/2613 which was closed but not yet resolved.

I created an extensive test suite for Metamorph datasets saved by Visitron's VisiView software:
https://github.com/fmi-basel/faim-imagej-bio-formats-tests

The relevant failing tests are:
```
[ERROR] testEqualTitles[benchmark_v1_2018_x64y64z1c2s1t11](ch.fmi.VisiViewFormatTest)  Time elapsed: 0.149 s  <<< FAILURE!
org.junit.ComparisonFailure: Image titles expected:<...rk_v1_2018_x64y64z1c[2s1t11_w1Laser4054BD4BP].tif> but was:<...rk_v1_2018_x64y64z1c[1s1t1].tif>
	at ch.fmi.VisiViewFormatTest.testEqualTitles(VisiViewFormatTest.java:108)

[ERROR] testEqualTitles[benchmark_v1_2018_x64y64z5c2s1t11](ch.fmi.VisiViewFormatTest)  Time elapsed: 0.16 s  <<< FAILURE!
org.junit.ComparisonFailure: Image titles expected:<...mark_v1_2018_x64y64z[5c2s1t11_w1Laser4054BD4BP.stk]> but was:<...mark_v1_2018_x64y64z[1c1s1t1.tif]>
	at ch.fmi.VisiViewFormatTest.testEqualTitles(VisiViewFormatTest.java:108)

[ERROR] testEqualTitles[benchmark_v1_2018_x64y64z5c2s1t41](ch.fmi.VisiViewFormatTest)  Time elapsed: 0.208 s  <<< FAILURE!
org.junit.ComparisonFailure: Image titles expected:<...mark_v1_2018_x64y64z[5c2s1t41_w1Laser4054BD4BP_t1.stk]> but was:<...mark_v1_2018_x64y64z[1c1s1t1.tif]>
	at ch.fmi.VisiViewFormatTest.testEqualTitles(VisiViewFormatTest.java:108)

[ERROR] testEqualTitles[benchmark_v1_2018_x64y64z5c2s4t41](ch.fmi.VisiViewFormatTest)  Time elapsed: 0.196 s  <<< FAILURE!
org.junit.ComparisonFailure: Image titles expected:<...mark_v1_2018_x64y64z[5c2s4t41_w1Laser4054BD4BP_s1_t1.stk] - Stage1 "Row0_Col0...> but was:<...mark_v1_2018_x64y64z[1c1s1t1.tif] - Stage1 "Row0_Col0...>
	at ch.fmi.VisiViewFormatTest.testEqualTitles(VisiViewFormatTest.java:108)
```

In all cases, identical files were read in, but from different folder locations (either isolated datasets, or a folder containing all of them).

**Comment by melissalinkert** [comment]
Thank you for the thorough test cases, @imagejan, and apologies for the delay in replying.  This is now linked to https://trello.com/c/823WSGPH/247-metamorph-incorrect-image-name-in-title-bar, and we'll update there with any progress.  We're aware that there are a number of outstanding (and in many cases interconnected) issues with Metamorph .nd/.stk datasets, which are captured in the ```Metamorph``` column here:

https://trello.com/b/IBHfAIMP/bio-formats-backlog

Closing this since the Trello card above tracks progress, but feel free to comment there.
