### ISSUE TITLE
Misspelling?

### ISSUE THREAD

**Issue by ebremer** [openmicroscopy/bioformats#3341]
https://docs.openmicroscopy.org/bio-formats/6.0.1/users/comlinetools/index.html

At the top of the page, "Note: As of Bio-Formats 5.0.0, this zip now contains the bundled jar and you no longer need to download loci_tools.jar or the new bioformats_package.jar separately. "

Should the 5.0.0 be 6.0.0?

**Comment by joshmoore** [comment]
No, it's been true longer. Just probably worth removing now! 🙂

**Comment by ebremer** [comment]
ah okay.  Was just wondering.
