### ISSUE TITLE
Why is ImageConverter private?

### ISSUE THREAD

**Issue by ebremer** [openmicroscopy/bioformats#3359]
Is there any reason why ImageConverter is "private ImageConverter()" instead of "public ImageConverter()"?

https://github.com/openmicroscopy/bioformats/blob/4d0f6757bed4e9b219ee9bfac575f1e924d9a2b9/components/bio-formats-tools/src/loci/formats/tools/ImageConverter.java#L118

**Comment by sbesson** [comment]
@ebremer thanks for raising this. I think the reason is largely historical as the constructor was introduced under a private scope in 1b0f9ada1e6fd1021bf0a45b277178c56a6e8e1b 12 years ago. I opened #3364 to publicize it in the next minor release of Bio-Formats.
