### ISSUE TITLE
bfconvert/ImageConverter -usemaximage

### ISSUE THREAD

**Issue by ebremer** [openmicroscopy/bioformats#3360]
Often I look in a WSI file and search for the series number of the largest image only.  I then convert that image to the new image format (usually tiff) and generate an image pyramid based on that image.  Could a "-usemaximage" be added to bfconvert/ImageConverter to do this?

**Comment by dgault** [comment]
Hi @ebremer, am I right that you are looking for it to automatically search for the image with the largest dimensions?

**Comment by ebremer** [comment]
Correct.

**Comment by ebremer** [comment]
Find the largest, ignore everything else and convert the largest image and construct a pyramid with the specified sizes and number.

**Comment by ebremer** [comment]
Writing this function myself.
