### ISSUE TITLE
openslide-show-properties doesn't show Bioformats generated image pyramid

### ISSUE THREAD

**Issue by ebremer** [openmicroscopy/bioformats#3374]
In using 6.0.1 (or even 6.1.0-m2) to convert a image from VSI->TIF (LZW compression) with a corresponding image pyramid appears to work fine from a bioformats point-of-view, but, when the file information is displayed with openslide-show-properties, it only shows the original image and not the pyramid.  Bioformats showinf shows it correctly.  Is this a openslide or a bioformats issue?

**Comment by sbesson** [comment]
@ebremer from our side, this is expected. Just like Bio-Formats, [OpenSlide](https://openslide.org/) will need a reader to detect a given file format and read sub-resolutions from the internal structure. Without this, OpenSlide probably detects pyramidal OME-TIFF files as a [Generic tiled TIFF](https://openslide.org/formats/generic-tiff/) with only its highest resolution.

Short answer is that Openslide support needs to happen at the level of https://github.com/openslide/openslide. Note also this [recent thread](https://lists.andrew.cmu.edu/pipermail/openslide-users/2019-March/001529.html) from the OpenSlide mailing list i.e. the capacity of the core OpenSlide team is limited at the moment but they will gladly take external contributions if someone invests into this extension.
