### ISSUE TITLE
new format: Plate format from GE DV Ultra

### ISSUE THREAD

**Issue by joshmoore** [openmicroscopy/bioformats#3394]
Requested in [[image.sc] https://forum.image.sc/t/bug-ge-deltavision-ultra-files/26860](https://forum.image.sc/t/bug-ge-deltavision-ultra-files/26860)

Sample data linked from the forum.

**Comment by melissalinkert** [comment]
I'd expect this to be fixed by https://github.com/openmicroscopy/bioformats/pull/3398

**Comment by dgault** [comment]
The sample file provided on the forum has been tested as part of the PR and is now included in the data repo. Closing this issue as the merged PR resolves the problem.
